import osg_types
  # File: ValueMap  was providing: osg::ValueMap
  # File: Vec3  was providing: osg::Vec3
  # File: LightSource  was providing: osg::LightSource
  # File: LOD  was providing: osg::LOD
  # File: Projection  was providing: osg::Projection
  # File: ClearNode  was providing: osg::ClearNode
  # File: Camera  was providing: osg::Camera
  # File: Sequence  was providing: osg::Sequence
  # File: Switch  was providing: osg::Switch
  # File: Geode  was providing: osg::Geode
  # File: ref_ptr  was providing: osg::ref_ptr
  # File: AutoTransform  was providing: osg::AutoTransform
  # File: Object  was providing: osg::Object
  # File: CoordinateSystemNode  was providing: osg::CoordinateSystemNode
  # File: PositionAttitudeTransform  was providing: osg::PositionAttitudeTransform
  # File: Referenced  was providing: osg::Referenced
  # File: CameraView  was providing: osg::CameraView
  # File: CullStack  was providing: osg::CullStack
  # File: TexGenNode  was providing: osg::TexGenNode
  # File: Transform  was providing: osg::Transform
  # File: Node  was providing: osg::Node, osg::NodePath
  # File: Geometry  was providing: osg::Geometry
  # File: Image  was providing: osg::Image
  # File: MatrixTransform  was providing: osg::MatrixTransform
  # File: Drawable  was providing: osg::Drawable
  # File: ClipNode  was providing: osg::ClipNode
  # File: Group  was providing: osg::Group
  # File: CopyOp  was providing: osg::CopyOp
  # File: ValueStack  was providing: osg::ValueStack
  # File: PagedLOD  was providing: osg::PagedLOD
  # File: ProxyNode  was providing: osg::ProxyNode
  # File: OccluderNode  was providing: osg::OccluderNode
  # File: Billboard  was providing: osg::Billboard
  # File: FrameStamp  was providing: osg::FrameStamp
  # File: OcclusionQueryNode  was providing: osg::OcclusionQueryNode
type
  TraversalMode* {.size:sizeof(cuint),header: "NodeVisitor", importcpp: "osg::NodeVisitor::TraversalMode", pure.} = enum
    TRAVERSE_NONE = 0,
    TRAVERSE_PARENTS = 1,
    TRAVERSE_ALL_CHILDREN = 2,
    TRAVERSE_ACTIVE_CHILDREN = 3

  VisitorType* {.size:sizeof(cuint),header: "NodeVisitor", importcpp: "osg::NodeVisitor::VisitorType", pure.} = enum
    NODE_VISITOR = 0,
    UPDATE_VISITOR = 1,
    EVENT_VISITOR = 2,
    COLLECT_OCCLUDER_VISITOR = 3,
    CULL_VISITOR = 4,
    INTERSECTION_VISITOR = 5

  DatabaseRequestHandler* {.header: "NodeVisitor", importcpp: "osg::NodeVisitor::DatabaseRequestHandler", byref.} = object #of osg::Referenced
    ## Callback for managing database paging, such as generated by PagedLOD
    ## nodes.

  ImageRequestHandler* {.header: "NodeVisitor", importcpp: "osg::NodeVisitor::ImageRequestHandler", byref.} = object #of osg::Referenced
    ## Callback for managing image paging, such as generated by PagedLOD
    ## nodes.

  NodeAcceptOp* {.header: "NodeVisitor", importcpp: "osg::NodeAcceptOp", byref.} = object
    ## Convenience functor for assisting visiting of arrays of osg::Node's.

  PushPopObject* {.header: "NodeVisitor", importcpp: "osg::PushPopObject", byref.} = object

  PushPopValue* {.header: "NodeVisitor", importcpp: "osg::PushPopValue", byref.} = object



{.push header: "NodeVisitor".}

proc constructNodeVisitor*(tm: TraversalMode): NodeVisitor {.constructor,importcpp: "osg::NodeVisitor::NodeVisitor(@)".}

proc constructNodeVisitor*(`type`: VisitorType, tm: TraversalMode): NodeVisitor {.constructor,importcpp: "osg::NodeVisitor::NodeVisitor(@)".}

proc constructNodeVisitor*(nv: NodeVisitor, copyop: CopyOp = SHALLOW_COPY): NodeVisitor {.constructor,importcpp: "osg::NodeVisitor::NodeVisitor(@)".}

proc constructDatabaseRequestHandler*(): DatabaseRequestHandler {.constructor,importcpp: "osg::NodeVisitor::DatabaseRequestHandler::DatabaseRequestHandler".}

proc constructImageRequestHandler*(): ImageRequestHandler {.constructor,importcpp: "osg::NodeVisitor::ImageRequestHandler::ImageRequestHandler".}

proc constructNodeAcceptOp*(nv: NodeVisitor): NodeAcceptOp {.constructor,importcpp: "osg::NodeAcceptOp::NodeAcceptOp(@)".}

proc constructNodeAcceptOp*(naop: NodeAcceptOp): NodeAcceptOp {.constructor,importcpp: "osg::NodeAcceptOp::NodeAcceptOp(@)".}

proc constructPushPopObject*(nv: ptr NodeVisitor , key: ptr Referenced , value: ptr Object ): PushPopObject {.constructor,importcpp: "osg::PushPopObject::PushPopObject(@)".}

proc constructPushPopObject*(valueStack: ptr ValueStack , key: ptr Referenced , value: ptr Object ): PushPopObject {.constructor,importcpp: "osg::PushPopObject::PushPopObject(@)".}

proc cloneType*(this: NodeVisitor): ptr Object   {.importcpp: "cloneType".}

proc clone*(this: NodeVisitor, copyop: CopyOp): ptr Object   {.importcpp: "clone".}

proc isSameKindAs*(this: NodeVisitor, obj: ptr Object ): bool  {.importcpp: "isSameKindAs".}

proc libraryName*(this: NodeVisitor): cstring  {.importcpp: "libraryName".}

proc className*(this: NodeVisitor): cstring  {.importcpp: "className".}

proc asNodeVisitor*(this: var NodeVisitor): ptr NodeVisitor   {.importcpp: "asNodeVisitor".}
    ## Convert 'this' into a NodeVisitor pointer if Object is a NodeVisitor,
    ## otherwise return 0. Equivalent to dynamic_cast<NodeVisitor*>(this).

proc asNodeVisitor*(this: NodeVisitor): ptr NodeVisitor   {.importcpp: "asNodeVisitor".}
    ## convert 'const this' into a const NodeVisitor pointer if Object is a
    ## NodeVisitor, otherwise return 0. Equivalent to dynamic_cast<const
    ## NodeVisitor*>(this).

proc asUpdateVisitor*(this: var NodeVisitor): ptr UpdateVisitor   {.importcpp: "asUpdateVisitor".}
    ## Convert 'this' into a osgUtil::UpdateVisitor pointer if Object is a
    ## osgUtil::UpdateVisitor, otherwise return 0. Equivalent to
    ## dynamic_cast<osgUtil::UpdateVisitor*>(this).

proc asUpdateVisitor*(this: NodeVisitor): ptr UpdateVisitor   {.importcpp: "asUpdateVisitor".}
    ## convert 'const this' into a const osgUtil::UpdateVisitor pointer if
    ## Object is a osgUtil::UpdateVisitor, otherwise return 0. Equivalent to
    ## dynamic_cast<const osgUtil::UpdateVisitor*>(this).

proc asCullVisitor*(this: var NodeVisitor): ptr CullVisitor   {.importcpp: "asCullVisitor".}
    ## Convert 'this' into a osgUtil::CullVisitor pointer if Object is a
    ## osgUtil::CullVisitor, otherwise return 0. Equivalent to
    ## dynamic_cast<osgUtil::CullVisitor*>(this).

proc asCullVisitor*(this: NodeVisitor): ptr CullVisitor   {.importcpp: "asCullVisitor".}
    ## convert 'const this' into a const osgUtil::CullVisitor pointer if
    ## Object is a osgUtil::CullVisitor, otherwise return 0. Equivalent to
    ## dynamic_cast<const osgUtil::CullVisitor*>(this).

proc asEventVisitor*(this: var NodeVisitor): ptr EventVisitor   {.importcpp: "asEventVisitor".}
    ## Convert 'this' into a osgGA::EventVisitor pointer if Object is a
    ## osgGA::EventVisitor, otherwise return 0. Equivalent to
    ## dynamic_cast<osgGA::EventVisitor*>(this).

proc asEventVisitor*(this: NodeVisitor): ptr EventVisitor   {.importcpp: "asEventVisitor".}
    ## convert 'const this' into a const osgGA::EventVisitor pointer if
    ## Object is a osgGA::EventVisitor, otherwise return 0. Equivalent to
    ## dynamic_cast<const osgGA::EventVisitor*>(this).

proc asIntersectionVisitor*(this: var NodeVisitor): ptr IntersectionVisitor   {.importcpp: "asIntersectionVisitor".}
    ## Convert 'this' into a osgUtil::IntersectionVisitor pointer if Object
    ## is a IntersectionVisitor, otherwise return 0. Equivalent to
    ## dynamic_cast<osgUtil::IntersectionVisitor*>(this).

proc asIntersectionVisitor*(this: NodeVisitor): ptr IntersectionVisitor   {.importcpp: "asIntersectionVisitor".}
    ## convert 'const this' into a const osgUtil::IntersectionVisitor pointer
    ## if Object is a IntersectionVisitor, otherwise return 0. Equivalent to
    ## dynamic_cast<const osgUtil::IntersectionVisitor*>(this).

proc asCullStack*(this: var NodeVisitor): ptr CullStack   {.importcpp: "asCullStack".}
    ## Convert 'this' into a osg::CullStack pointer if Object is a
    ## osg::CullStack, otherwise return 0. Equivalent to
    ## dynamic_cast<osg::CullStack*>(this).

proc asCullStack*(this: NodeVisitor): ptr CullStack   {.importcpp: "asCullStack".}
    ## convert 'const this' into a const osg::CullStack pointer if Object is
    ## a osg::CullStack, otherwise return 0. Equivalent to dynamic_cast<const
    ## osg::CullStack*>(this).

proc reset*(this: var NodeVisitor)  {.importcpp: "reset".}
    ## Method to call to reset visitor. Useful if your visitor accumulates
    ## state during a traversal, and you plan to reuse the visitor. To flush
    ## that state for the next traversal: call reset() prior to each
    ## traversal.

proc setVisitorType*(this: var NodeVisitor, `type`: VisitorType)  {.importcpp: "setVisitorType".}
    ## Set the VisitorType, used to distinguish different visitors during
    ## traversal of the scene, typically used in the Node::traverse() method
    ## to select which behaviour to use for different types of
    ## traversal/visitors.

proc getVisitorType*(this: NodeVisitor): VisitorType  {.importcpp: "getVisitorType".}
    ## Get the VisitorType.

proc setTraversalNumber*(this: var NodeVisitor, fn: cuint)  {.importcpp: "setTraversalNumber".}
    ## Set the traversal number. Typically used to denote the frame count.

proc getTraversalNumber*(this: NodeVisitor): cuint  {.importcpp: "getTraversalNumber".}
    ## Get the traversal number. Typically used to denote the frame count.

proc setFrameStamp*(this: var NodeVisitor, fs: ptr FrameStamp )  {.importcpp: "setFrameStamp".}
    ## Set the FrameStamp that this traversal is associated with.

proc getFrameStamp*(this: NodeVisitor): ptr FrameStamp   {.importcpp: "getFrameStamp".}
    ## Get the FrameStamp that this traversal is associated with.

proc setTraversalMask*(this: var NodeVisitor, mask: NodeMask)  {.importcpp: "setTraversalMask".}
    ## Set the TraversalMask of this NodeVisitor. The TraversalMask is used
    ## by the NodeVisitor::validNodeMask() method to determine whether to
    ## operate on a node and its subgraph. validNodeMask() is called
    ## automatically in the Node::accept() method before any call to
    ## NodeVisitor::apply(), apply() is only ever called if validNodeMask
    ## returns true. Note, if NodeVisitor::_traversalMask is 0 then all
    ## operations will be switched off for all nodes. Whereas setting both
    ## _traversalMask and _nodeMaskOverride to 0xffffffff will allow a
    ## visitor to work on all nodes regardless of their own Node::_nodeMask
    ## state.

proc getTraversalMask*(this: NodeVisitor): NodeMask  {.importcpp: "getTraversalMask".}
    ## Get the TraversalMask.

proc setNodeMaskOverride*(this: var NodeVisitor, mask: NodeMask)  {.importcpp: "setNodeMaskOverride".}
    ## Set the NodeMaskOverride mask. Used in validNodeMask() to determine
    ## whether to operate on a node or its subgraph, by OR'ing
    ## NodeVisitor::_nodeMaskOverride with the Node's own Node::_nodeMask.
    ## Typically used to force on nodes which may have been switched off by
    ## their own Node::_nodeMask.

proc getNodeMaskOverride*(this: NodeVisitor): NodeMask  {.importcpp: "getNodeMaskOverride".}
    ## Get the NodeMaskOverride mask.

proc validNodeMask*(this: NodeVisitor, node: Node): bool  {.importcpp: "validNodeMask".}
    ## Method to called by Node and its subclass' Node::accept() method, if
    ## the result is true it is used to cull operations of nodes and their
    ## subgraphs. Return true if the result of a bit wise and of the
    ## NodeVisitor::_traversalMask with the bit or between
    ## NodeVistor::_nodeMaskOverride and the Node::_nodeMask. default values
    ## for _traversalMask is 0xffffffff, _nodeMaskOverride is 0x0, and
    ## osg::Node::_nodeMask is 0xffffffff.

proc setTraversalMode*(this: var NodeVisitor, mode: TraversalMode)  {.importcpp: "setTraversalMode".}
    ## Set the traversal mode for Node::traverse() to use when deciding which
    ## children of a node to traverse. If a NodeVisitor has been attached via
    ## setTraverseVisitor() and the new mode is not TRAVERSE_VISITOR then the
    ## attached visitor is detached. Default mode is TRAVERSE_NONE.

proc getTraversalMode*(this: NodeVisitor): TraversalMode  {.importcpp: "getTraversalMode".}
    ## Get the traversal mode.

proc setValueMap*(this: var NodeVisitor, ps: ptr ValueMap )  {.importcpp: "setValueMap".}
    ## Set the ValueMap used to store Values that can be reused over a series
    ## of traversals.

proc getValueMap*(this: var NodeVisitor): ptr ValueMap   {.importcpp: "getValueMap".}
    ## Get the ValueMap.

proc getValueMap*(this: NodeVisitor): ptr ValueMap   {.importcpp: "getValueMap".}
    ## Get the ValueMap.

proc getOrCreateValueMap*(this: var NodeVisitor): ptr ValueMap   {.importcpp: "getOrCreateValueMap".}
    ## Get the ValueMap.

proc setValueStack*(this: var NodeVisitor, ps: ptr ValueStack )  {.importcpp: "setValueStack".}
    ## Set the ValueStack used to stack Values during traversal.

proc getValueStack*(this: var NodeVisitor): ptr ValueStack   {.importcpp: "getValueStack".}
    ## Get the ValueStack.

proc getValueStack*(this: NodeVisitor): ptr ValueStack   {.importcpp: "getValueStack".}
    ## Get the const ValueStack.

proc getOrCreateValueStack*(this: var NodeVisitor): ptr ValueStack   {.importcpp: "getOrCreateValueStack".}
    ## Get the ValueStack.

proc traverse*(this: var NodeVisitor, node: Node)  {.importcpp: "traverse".}
    ## Method for handling traversal of a nodes. If you intend to use the
    ## visitor for actively traversing the scene graph then make sure the
    ## accept() methods call this method unless they handle traversal
    ## directly.

proc pushOntoNodePath*(this: var NodeVisitor, node: ptr Node )  {.importcpp: "pushOntoNodePath".}
    ## Method called by osg::Node::accept() method before a call to the
    ## NodeVisitor::apply(..). The back of the list will, therefore, be the
    ## current node being visited inside the apply(..), and the rest of the
    ## list will be the parental sequence of nodes from the top most node
    ## applied down the graph to the current node. Note, the user does not
    ## typically call pushNodeOnPath() as it will be called automatically by
    ## the Node::accept() method.

proc popFromNodePath*(this: var NodeVisitor)  {.importcpp: "popFromNodePath".}
    ## Method called by osg::Node::accept() method after a call to
    ## NodeVisitor::apply(..). Note, the user does not typically call
    ## popFromNodePath() as it will be called automatically by the
    ## Node::accept() method.

proc getNodePath*(this: var NodeVisitor): NodePath  {.importcpp: "getNodePath".}
    ## Get the non const NodePath from the top most node applied down to the
    ## current Node being visited.

proc getNodePath*(this: NodeVisitor): NodePath  {.importcpp: "getNodePath".}
    ## Get the const NodePath from the top most node applied down to the
    ## current Node being visited.

proc getEyePoint*(this: NodeVisitor): Vec3  {.importcpp: "getEyePoint".}
    ## Get the eye point in local coordinates. Note, not all NodeVisitor
    ## implement this method, it is mainly cull visitors which will
    ## implement.

proc getViewPoint*(this: NodeVisitor): Vec3  {.importcpp: "getViewPoint".}
    ## Get the view point in local coordinates. Note, not all NodeVisitor
    ## implement this method, it is mainly cull visitors which will
    ## implement.

proc getDistanceToEyePoint*(this: NodeVisitor, a00: Vec3, a01: bool): cfloat  {.importcpp: "getDistanceToEyePoint".}
    ## Get the distance from a point to the eye point, distance value in
    ## local coordinate system. Note, not all NodeVisitor implement this
    ## method, it is mainly cull visitors which will implement. If the
    ## getDistanceFromEyePoint(pos) is not implemented then a default value
    ## of 0.0 is returned.

proc getDistanceFromEyePoint*(this: NodeVisitor, a00: Vec3, a01: bool): cfloat  {.importcpp: "getDistanceFromEyePoint".}
    ## Get the distance of a point from the eye point, distance value in the
    ## eye coordinate system. Note, not all NodeVisitor implement this
    ## method, it is mainly cull visitors which will implement. If the
    ## getDistanceFromEyePoint(pos) is not implemented than a default value
    ## of 0.0 is returned.

proc getDistanceToViewPoint*(this: NodeVisitor, a00: Vec3, a01: bool): cfloat  {.importcpp: "getDistanceToViewPoint".}
    ## Get the distance from a point to the view point, distance value in
    ## local coordinate system. Note, not all NodeVisitor implement this
    ## method, it is mainly cull visitors which will implement. If the
    ## getDistanceToViewPoint(pos) is not implemented then a default value of
    ## 0.0 is returned.

proc apply*(this: var NodeVisitor, drawable: Drawable)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, geometry: Geometry)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: Node)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: Geode)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: Billboard)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: Group)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: ProxyNode)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: Projection)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: CoordinateSystemNode)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: ClipNode)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: TexGenNode)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: LightSource)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: Transform)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: Camera)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: CameraView)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: MatrixTransform)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: PositionAttitudeTransform)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: AutoTransform)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: Switch)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: Sequence)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: LOD)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: PagedLOD)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: ClearNode)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: OccluderNode)  {.importcpp: "apply".}

proc apply*(this: var NodeVisitor, node: OcclusionQueryNode)  {.importcpp: "apply".}

proc requestNodeFile*(this: var DatabaseRequestHandler, fileName: string, nodePath: NodePath, priority: cfloat, framestamp: ptr FrameStamp , databaseRequest: ref_ptr[Referenced], options: ptr Referenced  = 0)  {.importcpp: "requestNodeFile".}

proc setDatabaseRequestHandler*(this: var NodeVisitor, handler: ptr DatabaseRequestHandler )  {.importcpp: "setDatabaseRequestHandler".}
    ## Set the handler for database requests.

proc getDatabaseRequestHandler*(this: var NodeVisitor): ptr DatabaseRequestHandler   {.importcpp: "getDatabaseRequestHandler".}
    ## Get the handler for database requests.

proc getDatabaseRequestHandler*(this: NodeVisitor): ptr DatabaseRequestHandler   {.importcpp: "getDatabaseRequestHandler".}
    ## Get the const handler for database requests.

proc getPreLoadTime*(this: ImageRequestHandler): cdouble  {.importcpp: "getPreLoadTime".}

proc readRefImageFile*(this: var ImageRequestHandler, fileName: string, options: ptr Referenced  = 0): ref_ptr[Image]  {.importcpp: "readRefImageFile".}

proc requestImageFile*(this: var ImageRequestHandler, fileName: string, attachmentPoint: ptr Object , attachmentIndex: cint, timeToMergeBy: cdouble, framestamp: ptr FrameStamp , imageRequest: ref_ptr[Referenced], options: ptr Referenced  = 0)  {.importcpp: "requestImageFile".}

proc setImageRequestHandler*(this: var NodeVisitor, handler: ptr ImageRequestHandler )  {.importcpp: "setImageRequestHandler".}
    ## Set the handler for image requests.

proc getImageRequestHandler*(this: var NodeVisitor): ptr ImageRequestHandler   {.importcpp: "getImageRequestHandler".}
    ## Get the handler for image requests.

proc getImageRequestHandler*(this: NodeVisitor): ptr ImageRequestHandler   {.importcpp: "getImageRequestHandler".}
    ## Get the const handler for image requests.

proc `()`*(this: var NodeAcceptOp, node: ptr Node )  {.importcpp: "# () #".}

proc `()`*(this: var NodeAcceptOp, node: ref_ptr[Node])  {.importcpp: "# () #".}

proc `=`*(this: var NodeAcceptOp, a00: NodeAcceptOp): NodeAcceptOp  {.importcpp: "# = #".}

{.pop.}  # header: "NodeVisitor"
