{.passL: "-losg -losgSim -losgAnimation -losgTerrain -losgDB -losgText -losgFX -losgUI -losgGA -losgUtil -losgManipulator -losgViewer -losgParticle -losgVolume -losgPresentation -losgWidget -losgShadow", passC:"-I/usr/include/osg" .}

import Material
import ValueMap
import Vec4us
import BoundsChecking
import Texture2DMultisample
import StateAttributeCallback
import Vec3
import State
import DeleteHandler
import CullSettings
import LightSource
import AttributeDispatchers
import BoundingSphere
import ViewportIndexed
import Vec3i
import NodeCallback
import GLExtensions
import LOD
import TexEnv
import Projection
import BlendColor
import ClearNode
import Vec4
import Camera
import Sequence
import Vec3s
import Vec2us
import BufferTemplate
import Switch
import Texture2D
import TemplatePrimitiveFunctor
import ShaderComposer
import Geode
import ref_ptr
import ArgumentParser
import Vec2s
import Observer
import Vec2b
import AutoTransform
import Fog
import Texture2DArray
import LightModel
import Object
import TriangleFunctor
import PolygonOffset
import BufferObject
import CoordinateSystemNode
import ConvexPlanarPolygon
import DispatchCompute
import Vec3ui
import Matrixf
import PositionAttitudeTransform
import Referenced
import ClusterCullingCallback
import Vec2ub
import CollectOccludersVisitor
import Types
import Texture3D
import ShadowVolumeOccluder
import Export
import ShadeModel
import CameraView
import ObserverNodePath
import LineWidth
import BlendEquation
import CullStack
import ShaderAttribute
import ScriptEngine
import Stats
import StateAttribute
import TexGen
import Array
import LineSegment
import ValueObject
import ComputeBoundsVisitor
import TexEnvCombine
import Plane
import Shape
import FrontFace
import Polytope
import Point
import os_utils
import ColorMaski
import Shader
import PrimitiveSet
import Version
import Vec2ui
import Math
import View
import ShapeDrawable
import ClipPlane
import LogicOp
import TextureBuffer
import ImageUtils
import TexGenNode
import GLU
import BlendEquationi
import BlendFunc
import OperationThread
import CullFace
import PolygonStipple
import Transform
import GL2Extensions
import Node
import Geometry
import TransferFunction
import Image
import TexMat
import Viewport
import buffered_value
import PolygonMode
import MatrixTransform
import ColorMask
import Drawable
import Timer
import ClipNode
import io_utils
import Vec3f
import Stencil
import Callback
import Group
import Vec3us
import Vec2
import ImageSequence
import BoundingBox
import ConvexPlanarOccluder
import Vec2f
import StateSet
import PrimitiveSetIndirect
import CopyOp
import Texture1D
import observer_ptr
import Hint
import Matrix
import BufferIndexBinding
import SampleMaski
import VertexProgram
import AudioStream
import ValueStack
import PrimitiveRestartIndex
import ColorMatrix
import ScissorIndexed
import StencilTwoSided
import DrawPixels
import Matrixd
import ApplicationUsage
import Vec3b
import Vec4b
import GraphicsCostEstimator
import DepthRangeIndexed
import PagedLOD
import TriangleLinePointIndexFunctor
import ProxyNode
import TextureRectangle
import TemplatePrimitiveIndexFunctor
import VertexArrayState
import OccluderNode
import AlphaFunc
import GLObjects
import Multisample
import GL
import LineStipple
import UserDataContainer
import AnimationPath
import GraphicsContext
import NodeTrackerCallback
import GraphicsThread
import ClampColor
import BindImageTexture
import BlendFunci
import CullingSet
import FragmentProgram
import Vec4ui
import TextureCubeMap
import Uniform
import RenderInfo
import PointSprite
import Vec3ub
import Vec4d
import Vec4s
import Sampler
import Light
import Depth
import Config
import VertexAttribDivisor
import Vec2i
import ClipControl
import Vec3d
import Vec2d
import fast_back_stack
import Scissor
import ContextData
import Billboard
import Quat
import FrameStamp
import Capability
import DisplaySettings
import Vec4ub
import OcclusionQueryNode
import GLDefines
import Identifier
import Program
import ImageStream
import Texture
import FrameBufferObject
import NodeVisitor
import KdTree
import Notify
import PatchParameter
import Endian
import Vec4i
import TexEnvFilter
import TriangleIndexFunctor
import MixinVector
import Vec4f
